# Generated by Django 2.2 on 2020-03-27 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_info', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IP',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=50)),
                ('ip_address', models.CharField(max_length=50)),
            ],
        ),
    ]
