# Generated by Django 2.2 on 2020-03-30 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_info', '0003_auto_20200330_1732'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ip',
            name='time_person',
        ),
        migrations.RemoveField(
            model_name='ip',
            name='time_rpa',
        ),
    ]
