# Generated by Django 2.2 on 2020-03-31 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_info', '0004_auto_20200330_1735'),
    ]

    operations = [
        migrations.CreateModel(
            name='Time',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flow', models.CharField(max_length=100)),
                ('time_rpa', models.CharField(max_length=50)),
                ('time_person', models.CharField(max_length=50)),
            ],
        ),
    ]
