# Generated by Django 2.2 on 2020-04-15 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_info', '0006_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后登录时间'),
        ),
    ]
