# Generated by Django 2.2 on 2020-04-15 09:04

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_info', '0007_user_login_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(default=django.utils.timezone.now, verbose_name='最后登录时间'),
        ),
    ]
