# Generated by Django 2.2 on 2020-04-16 02:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_info', '0008_auto_20200415_1704'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='login_time',
            field=models.DateTimeField(auto_now=True, verbose_name='最后登录时间'),
        ),
    ]
