# Generated by Django 2.2 on 2020-07-06 03:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_info', '0009_auto_20200416_1039'),
    ]

    operations = [
        migrations.AddField(
            model_name='rpa',
            name='end_time',
            field=models.CharField(max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='rpa',
            name='start_time',
            field=models.CharField(max_length=500, null=True),
        ),
    ]
