# Generated by Django 3.0.4 on 2020-03-24 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Rpa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('office', models.CharField(max_length=100)),
                ('flow_name', models.CharField(max_length=100)),
                ('finish', models.FloatField()),
                ('time_rpa', models.CharField(max_length=100, null=True)),
                ('time_person', models.CharField(max_length=100, null=True)),
                ('introduce', models.CharField(max_length=500, null=True)),
                ('remark', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
