# Generated by Django 2.0.13 on 2020-11-09 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowStatus',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='流程id')),
                ('flow_name', models.CharField(default='', max_length=100, verbose_name='流程名')),
                ('flow_num', models.CharField(default='', max_length=100, verbose_name='流程号')),
                ('start_time', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('result', models.CharField(default='', max_length=100, verbose_name='执行结果')),
            ],
        ),
    ]
