# Generated by Django 2.0.13 on 2020-11-10 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_command', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='MachineStatus',
            fields=[
                ('id', models.IntegerField(auto_created=True, primary_key=True, serialize=False, unique=True, verbose_name='流程id')),
                ('machine_ip', models.CharField(default='', max_length=100, verbose_name='机器ip')),
                ('machine_status', models.CharField(default='', max_length=100, verbose_name='执行状态')),
            ],
        ),
        migrations.AddField(
            model_name='flowstatus',
            name='machine_ip',
            field=models.CharField(default='', max_length=100, verbose_name='机器ip'),
        ),
    ]
