# Generated by Django 2.0.13 on 2020-11-10 05:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_command', '0002_auto_20201110_1124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flowstatus',
            name='flow_num',
            field=models.CharField(default='', max_length=100, unique=True, verbose_name='流程号'),
        ),
    ]
