# Generated by Django 2.0.13 on 2021-01-27 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FlowInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('name', models.CharField(max_length=50, verbose_name='流程名称')),
                ('workflow_id', models.IntegerField(verbose_name='工作流程节点id')),
                ('source_id', models.IntegerField(verbose_name='源点id')),
                ('destination_id', models.CharField(default='0', help_text='用于工单步骤接口时，指向的下一节点或并行的多个节点', max_length=150, verbose_name='目的状态id')),
                ('modify_last_man', models.CharField(max_length=150, verbose_name='最后修改流程的人')),
                ('run_state', models.IntegerField(default=0, help_text='0:未执行，1：正在执行，2：执行失败', verbose_name='运行状态')),
                ('run_info', models.CharField(default='', help_text='正在执行、运行失败、成功', max_length=150, verbose_name='运行状态信息')),
                ('last_run_info', models.CharField(default='', help_text='运行失败、成功', max_length=150, verbose_name='上一次运行状态信息')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
