# Generated by Django 2.0.13 on 2021-02-02 05:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_flowchart', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='FlowID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creator', models.CharField(max_length=50, verbose_name='创建人')),
                ('gmt_created', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('gmt_modified', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('is_deleted', models.BooleanField(default=False, verbose_name='已删除')),
                ('flow_name', models.CharField(max_length=50, verbose_name='流程名称')),
                ('workflow_id', models.IntegerField(verbose_name='流程节点id')),
                ('flow_state', models.IntegerField(default=0, help_text='0:未执行，1：正在执行，2：执行失败，3：执行完成', verbose_name='流程运行状态')),
                ('last_run_info', models.CharField(default='', help_text='运行失败、成功', max_length=150, verbose_name='上一次运行状态信息')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='flowinfo',
            name='workflow_id',
            field=models.IntegerField(verbose_name='所属工作流程节点id'),
        ),
    ]
