# Generated by Django 2.2 on 2020-04-28 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rpa_request', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='office',
            field=models.CharField(default='', max_length=100),
            preserve_default=False,
        ),
    ]
