/* This file is automatically generated. DO NOT EDIT! */

#ifndef _neighborsvti_h
#define _neighborsvti_h


#include <rsf.h>


void neighbors_init (int *in1     /* status flag [n[0]*n[1]*n[2]] */, 
		     float *rdx1  /* grid sampling [3] */, 
		     int *n1      /* grid samples [3] */, 
		     int order1   /* accuracy order */, 
		     float *time1 /* traveltime [n[0]*n[1]*n[2]] */,
		     float *itime1 /* isotropic traveltime [n[0]*n[1]*n[2]] */);
/*< Initialize >*/


int  neighbours(int i);
/*< Update neighbors of gridpoint i, return number of updated points >*/


int nearsource(float* xs   /* source location [3] */, 
	       int* b      /* constant-velocity box around it [3] */, 
	       float* d    /* grid sampling [3] */, 
	       float* vx2  /* horizontal slowness squared [n[0]*n[1]*n[2]] */,
	       float* vz2  /* vertical slowness squared */,
	       float* q2   /* non-ellipticity */,
	       bool *plane /* if plane-wave source */);
/*< initialize the source >*/

#endif
